version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  # Config Server
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=config-server
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    #volumes:
    #  - ./config-repo:/config-repo
  # Registry (Eureka)
  registry:
    build:
      context: ./registry
    container_name: registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=registry
      - CONFIG_SERVER_URL=http://config-server:9000
    networks:
      - app-network
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=api-gateway
      - CONFIG_SERVER_URL=http://config-server:9000
    networks:
      - app-network
    depends_on:
      registry:
        condition: service_healthy