spring:
  application:
    name: registry
server:
  port: 8761  # Puerto por defecto para Eureka Server

eureka:
  instance:
    hostname: registry
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false